VERİLERİN RANDOM FOREST İLE TAHMİN EDİLMESİ


In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import  RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


In [2]:
df = pd.read_csv('data_cleaned.csv')



In [3]:
df['city'] = df['city'].astype('category')
df['district'] = df['district'].astype('category')
df['neighborhood'] = df['neighborhood'].astype('category')
df['location'] = df['location'].astype('category')
df['room'] = df['room'].astype('int')
df['living_room'] = df['living_room'].astype('int')
df['area'] = df['area'].astype('int')
df['age'] = df['age'].astype('int')
df['floor'] = df['floor'].astype('int')
df['price'] = df['price'].astype('int')

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   location      197 non-null    category
 1   city          197 non-null    category
 2   district      197 non-null    category
 3   neighborhood  197 non-null    category
 4   room          197 non-null    int64   
 5   living_room   197 non-null    int64   
 6   area          197 non-null    int64   
 7   age           197 non-null    int64   
 8   floor         197 non-null    int64   
 9   price         197 non-null    int64   
dtypes: category(4), int64(6)
memory usage: 15.5 KB
None


In [4]:
categorical_features = ['city', 'district', 'neighborhood']
numerical_features = ['room', 'living_room', 'area', 'age', 'floor']

In [5]:
full_pipeline = ColumnTransformer([
    ('num', StandardScaler(), numerical_features),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
])


BU KISIMA KADAR REGRESYON İLE AYNI BURDAN SONRA FARKLILAŞIYOR

In [6]:
X = df.drop('price', axis=1)
y = df['price']

In [7]:
bins = [x for x in range(0, 8000000, 2000000)]
Labels = [x for x in range (1,5)]
print(bins)
print(Labels)

[0, 2000000, 4000000, 6000000]
[1, 2, 3, 4]


In [2]:
y= pd.cut(y , bins=bins ,labels=Labels)

NameError: name 'pd' is not defined

In [ ]:
print(y.unique())

[4350000 2300000 3250000 2950000 5750000 4100000 1200000 5950000 2600000
 2900000 3190000 5150000 6000000 1350000 4665000 2550000 4000000 2750000
 3650000 3700000 4500000 2340000 4200000 2250000 2500000 2425000 4490000
 4050000 4400000 2775000 2350000 4550000 3750000 1520000 3200000 1975000
 2450000 1300000 3550000 4480000 1750000 2400000 3350000 2580000 1800000
 2850000 3900000 3800000 3600000 2975000 2200000 1700000 1950000 4650000
 3100000 4850000 1775000 2000000 3000000 2700000 1460000 3950000 1497000
 1450000 2050000 6350000 5300000 2720000 1500000 4250000 1150000 1900000
 2650000 1650000 3500000 3450000 3300000 3850000 5200000 4025000 1525000
 3150000 1620000 5800000  920000 5000000 5250000 4690000 2890000 6600000
 4150000 3400000 1550000 1400000 1870000  655000 5500000 5400000 5100000
 4300000 2670000 2800000 2620000 1925000]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = Pipeline([
    ('preparation', full_pipeline),
    ('model', RandomForestClassifier(n_estimators=100, random_state=42))
])


In [ ]:
model.fit(X_train, y_train)

c:\Users\sema_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_type = type_of_target(y, input_name="y")
c:\Users\sema_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_type = type_of_target(y, input_name="y")
c:\Users\sema_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_type = type_of_target(y, input_name="y")
c:\Users\sema_\AppData\Local\Programs\Python\Python313\Lib\site-pac

Pipeline(steps=[('preparation',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['room', 'living_room',
                                                   'area', 'age', 'floor']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['city', 'district',
                                                   'neighborhood'])])),
                ('model', RandomForestClassifier(random_state=42))])

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]


c:\Users\sema_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\sema_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:99: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_pred = type_of_target(y_pred, input_name="y_pred")
c:\Users\sema_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
c:\Users\sema_\AppData\Loca

In [ ]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

      655000       0.00      0.00      0.00         1
     1150000       0.00      0.00      0.00         1
     1300000       0.00      0.00      0.00         0
     1450000       0.00      0.00      0.00         0
     1460000       0.00      0.00      0.00         0
     1497000       0.00      0.00      0.00         1
     1500000       0.00      0.00      0.00         1
     1550000       0.00      0.00      0.00         1
     1620000       0.00      0.00      0.00         1
     1650000       0.00      0.00      0.00         1
     1700000       0.00      0.00      0.00         1
     1775000       0.00      0.00      0.00         1
     1800000       0.00      0.00      0.00         0
     1975000       0.00      0.00      0.00         0
     2000000       0.00      0.00      0.00         1
     2050000       0.00      0.00      0.00         0
     2200000       0.00      0.00      0.00         1
     2250000       0.00    

c:\Users\sema_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\sema_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:99: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_pred = type_of_target(y_pred, input_name="y_pred")
c:\Users\sema_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
c:\Users\sema_\AppData\Loca